version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:80"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=rootpassword
      - DB_NAME=kualitas_udara
    depends_on:
      - db
    volumes:
      - .:/var/www/html

  db:
    image: mariadb:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=kualitas_udara
    volumes:
      - ./database/setup.sql:/docker-entrypoint-initdb.d/setup.sql
      - db_data:/var/lib/mysql

volumes:
  db_data:
